/** getting Random Image */

export const GET_RANDOM_IMAGE_REQUEST = 'GET_RANDOM_IMAGE_REQUEST';
export const GET_RANDOM_IMAGE_SUCCESS = 'GET_RANDOM_IMAGE_SUCCESS';
export const GET_RANDOM_IMAGE_FAILURE = 'GET_RANDOM_IMAGE_FAILURE';
